<a href="https://colab.research.google.com/github/Kumarkashish511/COGNITIVE_COMPUTING/blob/main/Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

Data={'tid':['1','2','3','4','5','6','7','8','9','10'],
      'Refund':['yes','no','no','yes','no','no','yes','no','no','no'],
      'Marital Status':['single','married','single','married','divorced','married','divorced','single','married','single'],
      'Taxable income':['125K','100K','70K','120K','95K','60K','220K','85K','75K','90K'],
      'Cheat':['no','no','no','no','yes','no','no','yes','no','yes']}

df = pd.DataFrame(Data)
print(df)

  tid Refund Marital Status Taxable income Cheat
0   1    yes         single           125K    no
1   2     no        married           100K    no
2   3     no         single            70K    no
3   4    yes        married           120K    no
4   5     no       divorced            95K   yes
5   6     no        married            60K    no
6   7    yes       divorced           220K    no
7   8     no         single            85K   yes
8   9     no        married            75K    no
9  10     no         single            90K   yes

In [5]:
result_loc=df.loc[[0,4,7,8],:]
print(result_loc)

  tid Refund Marital Status Taxable income Cheat
0   1    yes         single           125K    no
4   5     no       divorced            95K   yes
7   8     no         single            85K   yes
8   9     no        married            75K    no

In [6]:
selected_rows=df.iloc[3:8]
print(selected_rows)

  tid Refund Marital Status Taxable income Cheat
3   4    yes        married           120K    no
4   5     no       divorced            95K   yes
5   6     no        married            60K    no
6   7    yes       divorced           220K    no
7   8     no         single            85K   yes

In [7]:
selected_rows_column=df.iloc[4:9,2:5]
print(selected_rows_column)

  Marital Status Taxable income Cheat
4       divorced            95K   yes
5        married            60K    no
6       divorced           220K    no
7         single            85K   yes
8        married            75K    no

In [8]:
selected_terms=df.iloc[0:11,1:4]
print(selected_terms)

  Refund Marital Status Taxable income
0    yes         single           125K
1     no        married           100K
2     no         single            70K
3    yes        married           120K
4     no       divorced            95K
5     no        married            60K
6    yes       divorced           220K
7     no         single            85K
8     no        married            75K
9     no         single            90K

In [10]:
df=pd.read_csv('/content/Iris.csv')
print(df.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [11]:
df.drop([4],axis=0,inplace=True)
df.drop(['PetalLengthCm'],axis=1,inplace=True)
print(df)

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]

In [13]:
employee_data=pd.read_csv('/content/employee_data.csv')
employee_data.head()

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [14]:
employee_data.shape

(5, 10)

In [15]:
employee_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

In [16]:
employee_data.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

In [17]:
employee_data.head()

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [18]:
employee_data.tail(3)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [19]:
import numpy as np
average_salary=np.mean(employee_data['Salary'])
print(average_salary)

60000.0

In [20]:
bonus=np.sum(employee_data['Bonus'])
print(bonus)

27500

In [21]:
employee_age=np.min(employee_data['Age'])
print(employee_age)

28

In [22]:
highest_rating=np.max(employee_data['Rating'])
print(highest_rating)

4.7

In [23]:
employee_data.sort_values(by=['Salary'],ascending=False)
print(employee_data)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [24]:
def categorize_performance(rating):
  if rating >= 4.5:
    return 'Excellent'
  elif rating >= 4.0:
    return 'Good'
  else:
    return 'Average'

employee_data['Performance Category'] = employee_data['Rating'].apply(categorize_performance)
employee_data

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [25]:
missing_values = employee_data.isnull().sum()
missing_values

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance Category    0
dtype: int64

In [27]:
Rename_data = employee_data.rename(columns = {'Employee_ID':'ID'})
Rename_data

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [29]:
employee_data.loc[(employee_data['Years_of_Experience']>5)]

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [30]:
employee_data[(employee_data['Department']=='IT')]

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

In [31]:
def tax(salary):
  return (salary*0.1)

employee_data['Tax'] = employee_data['Salary'].apply(tax)
employee_data

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

In [32]:
employee_data.to_csv('modified_data.csv', index=False)